schemaVersion: 2.0.0
commandTests:
  - name: "First test"
    command: "sh"
    args: ["-c", "ls -l | wc -l"]
    expectedOutput: ["4"]

  - name: "Are we using 'nemo' user?"  # should use metadataTest, waiting for https://github.com/GoogleContainerTools/container-structure-test/pull/274#issuecomment-943424309
    command: "whoami"
    expectedOutput: ["nemo"]

fileExistenceTests:
- name: 'Pure Test directory exists'
  path: '/tmp/.pure/'
  shouldExist: true
  permissions: 'drwxr-xr-x'
  uid: 1000
  gid: 1000
  isExecutableBy: 'group'

metadataTest:
  workdir: "/tmp/.pure/"
  entrypoint: ["fish", "-c"]
  cmd: ["fishtape tests/*.test.fish"]